// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhcgcgovgjxsgmtkimye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoY2djZ292Z2p4c2dtdGtpbXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTYwODUsImV4cCI6MjA2MzMzMjA4NX0.ec8oTIO_9X4veDY8kLI2A-8Cnnhm3JtTWo8MKz4E4HU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);